### PR TITLE
Allow rebasing peripherals

### PR DESCRIPTION
**Pull request by psycowithespn**
This is the implementation of my idea in #97.

Specify in a device yaml as follows (I'm sure this can be improved, just not sure how):
```yaml
_rebase:
  I2C1: I2C3
```

It was a coin toss as to when the rebase occurs, before or after modifying peripherals.

### CODE REVIEW

**Comment by adamgreig** [comment]
Nice! I'll have time to check this more carefully tomorrow evening, but perhaps you could include a second commit in this PR showing some example uses in the existing YAMLs? It will help check what it should do and also ensure the CI passes.

**Comment by adamgreig** [comment]
Could you also add an example usage to the project README, since that's where all the patch options are currently documented?

**Comment by psycowithespn** [comment]
Done and done.

I've noticed that this can mess with spacing of the rebased peripheral of the resulting svd. Looks like just the first moved element, though. Is this an issue?

**Comment by adamgreig** [comment]
Thanks!

> I've noticed that this can mess with spacing of the rebased peripheral of the resulting svd.

Just whitespace changes don't matter. You can tweak this using `Element.tail` [like this](https://github.com/adamgreig/stm32-rs/blob/master/scripts/svdpatch.py#L101) if you want.

This looks good to me and I can see the use case for the HALs, but it's definitely a breaking change so I'm going to wait on merging it until svd2rust 0.14 comes out and we can do a big break to 0.5 with the new svd2rust as well.

**Comment by psycowithespn** [comment]
> You can tweak this using `Element.tail` [like this](https://github.com/adamgreig/stm32-rs/blob/master/scripts/svdpatch.py#L101) if you want.

Thanks for the hint. XPath's last() didn't seem to work right, so I had to resort to 2 loops.

**Comment by adamgreig** [comment]
On second thoughts I'll merge this into master here now so we can start using it, and then it will just be included in the next release, which will be 0.5 and come out once svd2rust 0.14 is done.

**Pull request merged**
