### PR TITLE
Add a sticky header and first columns to Peripheral Compare page

### PR DESCRIPTION
**Pull request by octronics**
Helps a lot when searching on which family peripheral exists. CSS only implementation. Tested on firefox.  
The styling can be improve, but first let me know if that seems a good idea.

### CODE REVIEW

**Comment by adamgreig** [comment]
I like the idea and it works for me in Firefox but only the column sticks in Chrome, not the top row. Not sure why...

**Comment by octronics** [comment]
Perhaps those can help:
```
position: -webkit-sticky;
position: -moz-sticky;
position: -ms-sticky;
position: -o-sticky;
```
I don't have a chrome browser so can't test them.

**Comment by adamgreig** [comment]
It turns out to be [this](https://stackoverflow.com/questions/44001954/css-only-sticky-table-headers-in-chrome), making the selector `table thead tr th` solves it.

Maybe it would be worth adding to the other tables too?

**Comment by octronics** [comment]
I can take a look at it. But don't expect something before next week.

**Comment by adamgreig** [comment]
:+1: no worries. Thanks for the other PRs too!

**Comment by octronics** [comment]
Refactors page generation by adding the table on a template with minimal markup to have valid web page. Also gives page a title. And cleanups.

**Comment by adamgreig** [comment]
This looks good!

The sticky headers still don't work in Chrome: they need `table thead tr th` for the selector, but we don't have the final `th` here at the moment. I'm happy with all the rest.

**Comment by octronics** [comment]
Done. Can you test it with chrome. While at it, I catch a small visual glitch.

**Comment by octronics** [comment]
Sorry I press the wrong button.

**Comment by adamgreig** [comment]
Works fine, thank you!

**Comment by adamgreig** [comment]
I've updated the hosted version ([here](https://agg.io/u/stm32)) and added a script `htmlcomparesvdall.sh` which generates that version (i.e. runs for each family and makes a top level summary etc).

**Pull request merged**
